/**
 * Public Typeform URL for “Request audit” (no secret here).
 * Generated by scripts/create-typeform-audit.mjs — do not edit by hand.
 */
export const AUDIT_FORM_URL_FROM_REPO = "https://form.typeform.com/to/MVV0qYL9";
